### ISSUE TITLE
Tutorial isn't finished

### ISSUE THREAD

**Issue by lifeiscontent** [codeschool/AppEvolutionWithSwiftDemo#1]
You guys never rewired the contact view controller back up in the app...

what gives?

**Comment by lifeiscontent** [comment]
ping @jonfriskics

**Comment by jonfriskics** [comment]
We ended up moving that over to the Soup to Bits project video that will be posted on Monday.  Once that video is out we'll add that updated project to this repo in a different folder.

**Comment by jonfriskics** [comment]
Soup to Bits was just released so check `master` again for the updated code!

**Comment by lifeiscontent** [comment]
@jonfriskics cool thanks! Any plans to do a tutorial that covers UI without story board? No real app devs use story board in production...

**Comment by jonfriskics** [comment]
No plans for full courses without Storyboards, but it's possible that we'll have some screencasts at some point.  Storyboards have actually improved a lot over the years and they are much easier to work with in teams now, so plenty of app devs use them - especially now with the need for adaptive layout.
